services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_hw
    environment:
      POSTGRES_DB: file_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  storage:
    build: storage
    container_name: storage_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/file_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  analysis:
    build: analysis
    container_name: analysis_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/file_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    build: gateway
    container_name: gateway_app
    ports:
      - "8080:8080"
volumes:
  postgres_data: