grpc:
  client:
    report-service:
      address: 'static://localhost:9090' # Порт grpc основного приложения
      negotiation-type: plaintext

telegram:
  bot:
    username: test12312332199901_bot
    token: 7881565931:AAGRjSIuf0duTwPzkRinLhYBWMBoRncg_to
    chat-id: 895736614
