spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: false
  eureka:
    client:
      enabled: false
  cloud:
    gateway:
      routes:
        - id: storage-swagger
          uri: http://storage:8081
          predicates:
            - Path=/api/files/**

        - id: analysis-swagger
          uri: http://analysis:8082
          predicates:
            - Path=/api/analysis/**
server:
  port: 8080