services:
  postgres-storage:
    image: postgres:15-alpine
    container_name: postgres-db-storage
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_stor:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    depends_on:
      - storage
    ports:
      - "8080:8080"

  analysis:
    build:
      context: ./analysis
      dockerfile: Dockerfile
    container_name: analysis
    depends_on:
      - storage
    ports:
      - "8082:8080"

  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile
    container_name: storage_service
    depends_on:
      - postgres-storage
    ports:
      - "8081:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.22.0
    restart: always
    ports:
      - "8083:8080"
    environment:
      URLS: >
        [
          { name: 'Storage', url: 'http://localhost:8081/api' },
          { name: 'Analysis', url: 'http://localhost:8082/api' },
          { name: 'Gateway', url: 'http://localhost:8080/api'}
        ]

volumes:
  postgres_data_stor:
